### ISSUE TITLE
File README.md was not found in the repository

### ISSUE THREAD

**Issue by hertzg** [all-contributors/app#332] opened 2020-12-28 14:16 UTC
**Describe the bug**
When requesting all-contributors (bot) to add someone for something it fails with message (see screenshot) `File README.md was not found in the repository`. The [file does exist](https://github.com/hertzg/node-net-keepalive/blob/master/README.md) with the exact same name in the root of the repository.

A similar command used to work around 20 days ago. (see screenshot)

**To Reproduce**
1. Go to a repository that is configured to give access to the bot
2. Request bot to add someone for something
4. See bot reporting README.md not found error

**Expected behavior**
A PR being created with the requested action

**Screenshots**

Source: https://github.com/hertzg/node-net-keepalive/pull/8#issuecomment-751723618

20 days ago:
![image](https://user-images.githubusercontent.com/1886698/103219757-e41ec380-491e-11eb-99b0-741c7b635ca8.png)

just recently:
![image](https://user-images.githubusercontent.com/1886698/103219732-d5d0a780-491e-11eb-9540-5d7348760dfc.png)

**Comment by gr2m** [comment] 2020-12-29 20:27
Hi @hertzg, I've been working at the app's code in #330 but I don't know what might have happened. Once I finish #330 and we deploy to Vercel and drain logs to Logflare, it will be easier to find out the cause of a problem such as yours. We have Sentry setup but there is no error related to your issue. Bear with me, we should be able to ship #330 soon

**Comment by Berkmann18** [comment] 2020-12-30 16:28
I've looked at your repo and can't seem to find why that error popped up. Sentry doesn't show any issues dating to when you got that message.

**Comment by hertzg** [comment] 2020-12-30 17:55
Can I help with detecting the issue in some way?

**Comment by Berkmann18** [comment] 2020-12-30 19:24
@hertzg Here are some things you could try:
- trying again in the same PR,
- trying in an issue (it could be a new one),
- doing what you asked the bot to do but with the CLI,
- re-installing the bot and trying again

**Comment by hertzg** [comment] 2020-12-31 09:28
> @hertzg Here are some things you could try:
> 
> * trying again in the same PR,
> * trying in an issue (it could be a new one),
> * doing what you asked the bot to do but with the CLI,
> * re-installing the bot and trying again

- [X] trying again in the same PR - 🛑 https://github.com/hertzg/node-net-keepalive/pull/8#issuecomment-752900310
- [X] trying in an issue (it could be a new one), - 🛑 https://github.com/hertzg/node-net-keepalive/issues/151
- [X] doing what you asked the bot to do but with the CLI, - ✔️ - https://github.com/hertzg/node-net-keepalive/commit/54e05af6495d98ea49743859e4b69d08647f8c42
- [X] re-installing the bot and trying again - 🛑 - https://github.com/hertzg/node-net-keepalive/pull/8#issuecomment-752901197

**Comment by Berkmann18** [comment] 2020-12-31 12:30
Hmm, that's bizarre.
I wonder if the fact the bot uses `all-contributors-cli@v6.12` instead of a more recent version like `v6.19` would help in resolving this.
#330 uses the latest version and should make it easier to diagnose issues.

**Comment by hertzg** [comment] 2021-01-02 18:17
Happy new year 🎆 

I'm not sure how to help check that..

**Comment by gr2m** [comment] 2021-01-02 20:35
@hertzg can you try again, please? The app is now running on the latest probot, the problem might be resolved. If not, I should see something in the logs

**Comment by hertzg** [comment] 2021-01-03 12:56
Hello @gr2m, The `README` issue is gone 🎉  but seems like now other issues appeared:

* When I requested to add myself for something new the bot created a pr with totally new .all-contributors (removed everyone else)

This was probably because it did not fetch the local git from origin/upstream master because the commit from where it branched of is
> 15 commits behind master.
![image](https://user-images.githubusercontent.com/1886698/103479015-c0e68f00-4dca-11eb-8171-039b0f634941.png)


* After when I requested for someone else who already exists in the list it seems to have fetched the latest commit before pushing but the changelog is empty.

![image](https://user-images.githubusercontent.com/1886698/103479073-49652f80-4dcb-11eb-8f2a-dba0db61dfb2.png)

![image](https://user-images.githubusercontent.com/1886698/103479051-128f1980-4dcb-11eb-92e0-de4defd9f1cc.png)

Please have a look here: https://github.com/hertzg/node-net-keepalive/issues/152

I can close this issue as resolved and create a new one stemming from this. What do you think?

**Comment by gr2m** [comment] 2021-01-03 21:48
> I can close this issue as resolved and create a new one stemming from this. What do you think?

Yes please, others might run into the same problem. A new issue will make it easier from the to recognize and we avoid duplicates.

**Closed** 2021-01-03 22:43 UTC
Labels: bug
