### ISSUE TITLE
Doesn't recognize hyphens in a user's name (at the end of their name)?

### ISSUE THREAD

**Issue by jpivarski** [all-contributors/app#310] opened 2020-05-08 15:00 UTC
See https://github.com/scikit-hep/awkward-1.0/pull/238

I attempted to add `@nsmith-` (name ends in a hyphen) and it didn't work the first time (don't know why), but a trivial change in the list of roles (removed Oxford comma) caused the bot to add `@nsmith` without a hyphen.

I'm now editing the pull request by hand.

**Comment by baikho** [comment] 2020-05-22 06:31
Hi @jpivarski,
I believe this is a duplicate of https://github.com/all-contributors/all-contributors-bot/issues/292 and PR #307 . Do we need to tag a new release for these changes to take effect @Berkmann18 ?

**Comment by Berkmann18** [comment] 2020-05-22 14:27
@baikho Normally no, as it's done automatically.
I noticed your PR didn't get a response from the release bot which makes me wonder what went wrong.

**Comment by rkdarst** [comment] 2020-10-02 07:53
I just got hit with this: I used the bot to add a contributor with github login `firstname-lastname`, and the bot added `firstname` (a different person) as a contributor!  https://github.com/rkdarst/all-contributors-test/issues/2

**Comment by reobin** [comment] 2020-10-02 12:59
Seems like this is still an issue, even when using the `@` before the user name

![Screen Shot 2020-10-02 at 08 58 20](https://user-images.githubusercontent.com/5920450/94925637-8993d980-048d-11eb-852f-b286df4b578c.png)

**Comment by Berkmann18** [comment] 2020-10-03 07:36
That seems to be due to the fact that the CI/CD pipeline didn't work on the @baikho's PR and I don't have admin rights there so I can't see exactly what went wrong.

**Comment by Berkmann18** [comment] 2021-01-18 20:52
@jpivarski The bot was rewritten and we've got a better logging system now, could you try again and we'll see if it's still an issue?

**Comment by tenshiAMD** [comment] 2022-09-13 08:21
> @jpivarski The bot was rewritten and we've got a better logging system now, could you try again and we'll see if it's still an issue?

@jpivarski Have you check this using latest version? Please check and let us know if this still occurs. Closing this for now. Thanks! 🎉

**Closed by tenshiAMD** 2022-09-13 08:21 UTC
Labels: bug, status: waiting for feedback
