### ISSUE TITLE
When contributor name contains a minus sign then allcontributors  loses the part after the minus sign

### ISSUE THREAD

**Issue by aaltat** [all-contributors/app#354] opened 2021-04-10 19:39 UTC
**Describe the bug**
If contributor name contains a minus sign, like foo-bar, then allcontributors  loses the part after the minus sign. Example foo-bar comes as foo-

**To Reproduce**
1) When I example says: `@all-contributors please add vincenzo-gasparo for code`
2) Then `Could not find the user vincenzo- on github.`

**Expected behavior**
Did expect user to be assed correctly.

**Comment by Berkmann18** [comment] 2021-04-14 21:26
Have you tried doing that with the CLI by any chance? If so, did you also got an error?

I've dug a bit deeper and this might be a regression as opposed to a bug (given that it worked for users who used the bot, although that was before it was rewritten).

**Comment by aaltat** [comment] 2021-04-16 20:57
I tried from command line and from command line user name was detected correctly.

**Comment by aaltat** [comment] 2021-04-16 21:09
Found the PR from our repository where the problem occurs: https://github.com/MarketSquare/robotframework-browser/issues/814#issuecomment-808869259

**Comment by mtfoley** [comment] 2021-05-02 12:50
FWIW, it looks like the parsing would work if using "@olga-zm". I added a couple of tests just to see what it would do.
![Screen Shot 2021-05-02 at 8 47 30 AM](https://user-images.githubusercontent.com/3792749/116813696-10438e80-ab23-11eb-8df0-8b50f08d5faf.png)
![Screen Shot 2021-05-02 at 8 49 17 AM](https://user-images.githubusercontent.com/3792749/116813744-5993de00-ab23-11eb-8101-fd3da948fc2a.png)

**Comment by Berkmann18** [comment] 2021-05-08 14:05
@mtfoley I see, feel free to submit a PR with your findings.

**Comment by mtfoley** [comment] 2021-05-08 16:14
@Berkmann18 I actually think you should close the issue and @aaltat should try using the bot with username mentions in the future. The changes introduced by the [merged PR #434](https://github.com/all-contributors/all-contributors/pull/434) for [all-contributors/all-contributors#413](https://github.com/all-contributors/all-contributors/issues/413) was to update the docs to show preceding contributor username with @. I think the docs ought to go one step further and explicitly state that the bot will match the username best if preceded with @ symbol. I'll submit a PR over there.

**Closed** 2021-05-08 21:00 UTC
Labels: status: waiting for feedback
