### ISSUE TITLE
Failing to ask the bot to credit a user for research work

### ISSUE THREAD

**Issue by Lucas-C** [all-contributors/app#365] opened 2021-07-08 10:53 UTC
**Describe the bug**
The `@all-contributors` bot fails to add the `research` contribution to an existing user (already in `.all-contributorsrc`)

**To Reproduce**
I simply used the following syntax:

    @all-contributors please add @moe-25 for research

**Expected behavior**
I expected the bot to create a commit on the repo that would add the new contribution to the user

**Screenshots**
<img width="685" alt="2021-07-08 12_52_45-Added support for emoticons by moe-25 · Pull Request #183 · PyFPDF_fpdf2" src="https://user-images.githubusercontent.com/925560/124910056-71885200-dfeb-11eb-9aec-c40127b90bda.png">

**Additional context**
Link to the issue where the problem appeared:
https://github.com/PyFPDF/fpdf2/pull/183#issuecomment-876335583

**Comment by Lucas-C** [comment] 2021-07-08 15:42
Note that it worked well later on for another type of contribution ("bug"):
https://github.com/PyFPDF/fpdf2/issues/184

**Comment by Lucas-C** [comment] 2021-07-15 09:43
It happened again for "review" contribution:
https://github.com/PyFPDF/fpdf2/pull/191#issuecomment-880546962

**Comment by gaocegege** [comment] 2022-06-28 13:57
Same behavior here.

**Comment by tenshiAMD** [comment] 2022-09-13 08:07
Duplicate of https://github.com/all-contributors/app/issues/399

**Closed by tenshiAMD** 2022-09-13 08:07 UTC
Labels: bug
