### ISSUE TITLE
Support PullRequestReviewCommentEvent

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/app#181] opened 2019-03-22 23:33 UTC
**Is your feature request related to a problem? Please describe.**
Support bot comments from https://developer.github.com/v3/activity/events/types/#pullrequestreviewcommentevent

**Comment by tenshiAMD** [comment] 2022-09-25 03:51
Duplicate of https://github.com/all-contributors/app/issues/152

**Closed by tenshiAMD** 2022-09-25 03:51 UTC
Labels: enhancement
