### ISSUE TITLE
We had trouble processing your request. Please try again later.

### ISSUE THREAD

**Issue by mmiszy** [all-contributors/app#447] opened 2022-12-05 14:55 UTC
**Describe the bug**
For a few weeks now I keep on getting this error message when I ping the bot in a comment under any PRs:

> We had trouble processing your request. Please try again later.

**To Reproduce**

1. Go to https://github.com/typeofweb/devfaq/pull/378
2. See my comment https://github.com/typeofweb/devfaq/pull/378#issuecomment-1337518543
3. See the error response https://github.com/typeofweb/devfaq/pull/378#issuecomment-1337518613

**Expected behavior**
No errors.

**Comment by tenshiAMD** [comment] 2022-12-24 10:34
Duplicate of https://github.com/all-contributors/app/issues/444.

**Closed by tenshiAMD** 2022-12-24 10:34 UTC
Labels: bug
